### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lnschema-bionty#79]
```
Traceback (most recent call last):
  File "/home/zeth/miniconda3/envs/bionty/bin/lamin", line 8, in <module>
    sys.exit(main())
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/lndb/__main__.py", line 103, in main
    result = _init_instance.init(
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/lndb/_init_instance.py", line 100, in init
    message = load(f"{owner}/{name_str}", _log_error_message=False, migrate=_migrate)
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/lndb/_load_instance.py", line 69, in load
    message = load_from_isettings(isettings, migrate)
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/lndb/_load_instance.py", line 103, in load_from_isettings
    persist_settings_load_schema(isettings)
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/lndb/_init_instance.py", line 49, in persist_settings_load_schema
    load_schema(isettings)
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/lndb/dev/_setup_schema.py", line 115, in load_schema
    module = check_schema_version_and_import(schema_name)
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/lndb/dev/_setup_schema.py", line 103, in check_schema_version_and_import
    raise import_error
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/lndb/dev/_setup_schema.py", line 97, in check_schema_version_and_import
    module = importlib.import_module(get_schema_module_name(schema_name))
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/lnschema_bionty/__init__.py", line 40, in <module>
    from ._core import (  # noqa
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/lnschema_bionty/_core.py", line 141, in <module>
    class Pathway(SQLModel, table=True):  # type: ignore
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/lnschema_bionty/dev/_bionty.py", line 48, in knowledge
    entity = Entity()
  File "/home/zeth/PycharmProjects/bionty/bionty/entities/_pathway.py", line 25, in __init__
    super().__init__(
  File "/home/zeth/PycharmProjects/bionty/bionty/_entity.py", line 69, in __init__
    self._set_attributes(database=database, version=version)
  File "/home/zeth/PycharmProjects/bionty/bionty/_settings.py", line 27, in wrapper
    return f(*args, **kwargs)
  File "/home/zeth/PycharmProjects/bionty/bionty/_entity.py", line 288, in _set_attributes
    self._url, self._md5 = (
TypeError: cannot unpack non-iterable NoneType object
```

Bionty: 0.11.3
lnschema-bionty: 0.14.0

**Comment by Zethson** [comment]
This may also just be a version mismatch somewhere because this error should be fixed in Bionty.

**Comment by Zethson** [comment]
Seems to have gotten fixed with the latest release
